version:  "3"
services:
  db:
    image:  mariadb:10.4
    comtainer_name: "laravel-db"
    volume:
      ./data:/var/lib/mysql
    ports:
      "3306:3306"
  php:
    build:build: ./php
    comtainer_name:build: "laravel-php"
    volume:
      ./source:/var/www/html
      ./php/vhost.conf:/etc/apache2/conf-enabled/vhost.conf
    ports:
      "8080:80"

