FROM php:7.3.29-apache
RUN apt-get update \
  && apt-get install -y zliblg-dev \
  && apt-get install -y zip unzip \
  && apt-get -y install libzip-dev \
  && docker-php-ext-install pdo_mysql mysqli mbstring zip\
  && docker-php-ext-enable mysqli \
  && a2emod rewite